spring:
  config:
    import: secrets.yml
  application:
    name: neon
  ai:
    azure:
      openai:
        endpoint: https://genai-openai-mitr.openai.azure.com/
        chat:
          options:
            deployment-name: gpt-4o
        embedding:
          options:
            model: embedding-model
server:
  port: 8080

azure:
  formrecognizer:
    endpoint: https://neon-document-intelligence.cognitiveservices.azure.com/
  search:
    endpoint: https://neon-searchservice.search.windows.net


