spring:
  config:
    import: secrets.yml
  application:
    name: neon
  ai:
    vectorstore:
      cosmosdb:
        endpoint: https://neon-cosmosdb.documents.azure.com:443/
        container-name: neon-cosmosdb-container
        database-name: neon-cosmosdb-database
        metadata-fields: ""
    azure:
      openai:
        endpoint: https://eastus2.api.cognitive.microsoft.com/
        chat:
          options:
            deployment-name: neon-gpt-4
        embedding:
          options:
            model: embedding-model
server:
  port: 8081

azure:
  formrecognizer:
    endpoint: https://eastus2.api.cognitive.microsoft.com/
  search:
    endpoint: https://neon-search-service.search.windows.net
    indexname: neon-contract-index
    semantic-search-config: neon-contract-semantic-config

